[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { sepolia-eth = "my-sepolia-endpoint", arb-sepolia = "my-arb-sepolia-endpoint" }
solc = "0.8.24"
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/',
    '@ccip=lib/ccip/',
    '@chainlink-local/=lib/chainlink-local/',
    #'forge-std/=lib/forge-std/src/',
] # See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
